-- CreateTable
CREATE TABLE "restaurant_settings" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL DEFAULT 'KURO',
    "description" TEXT,
    "phone" TEXT,
    "email" TEXT,
    "website" TEXT,
    "address" TEXT,
    "vatNumber" TEXT,
    "taxId" TEXT,
    "operatingHours" JSONB NOT NULL DEFAULT '[]',
    "reservationSlotIntervalMinutes" INTEGER NOT NULL DEFAULT 30,
    "reservationLunchDurationMinutes" INTEGER NOT NULL DEFAULT 90,
    "reservationDinnerDurationMinutes" INTEGER NOT NULL DEFAULT 120,
    "reservationMaxGuests" INTEGER NOT NULL DEFAULT 20,
    "reservationCancellationCutoffHours" INTEGER NOT NULL DEFAULT 2,
    "autoAssignTable" BOOLEAN NOT NULL DEFAULT true,
    "deliveryEnabled" BOOLEAN NOT NULL DEFAULT true,
    "takeawayEnabled" BOOLEAN NOT NULL DEFAULT true,
    "dineInEnabled" BOOLEAN NOT NULL DEFAULT true,
    "minOrderAmount" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "deliveryFee" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "estimatedPrepTimeMinutes" INTEGER NOT NULL DEFAULT 20,
    "cashEnabled" BOOLEAN NOT NULL DEFAULT true,
    "cardEnabled" BOOLEAN NOT NULL DEFAULT true,
    "satispayEnabled" BOOLEAN NOT NULL DEFAULT false,
    "edenredEnabled" BOOLEAN NOT NULL DEFAULT false,
    "pointsPerEuro" DECIMAL(10,2) NOT NULL DEFAULT 1,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "restaurant_settings_pkey" PRIMARY KEY ("id")
);
